title = "Custom ruleset"

[[rules]]
description = "Ignore demo Airflow/Postgres creds"
regex = '''postgresql:\/\/(airflow|postgres):airflow@postgres\/airflow'''
tags = ["ignore", "demo"]
[rules.allowlist]
  paths = [
    "scheduler/compose.airflow.yml",
    "scheduler/compose.yml",
    "scheduler/config/airflow.cfg"
  ]
